### PR TITLE
Support building with iOS and tvOS device SDKs (or other platforms with non x86_64 CPU)

### LINKED ISSUE #17: Can't be built for real devices (iOS and tvOS)
https://github.com/mattgallagher/CwlPreconditionTesting/commit/fd66a0bab044b84b27c13e066309079973de1284 the commit did break the builds for real iOS and tvOS devices whose arch is not x86_64. It should be possible to run a test suite on real devices (e.g. in AWS Device Farm or Firebase Test Lab) including this library with excluding the usages (gated with `#if arch(x86_64)`). Is it okay to re-add `#if arch(x86_64)` check?

### PR DESCRIPTION
**Pull request by ikesyo**
Closes #17.

### CODE REVIEW

**Comment by ikesyo** [comment]
@mattgallagher Could you take a look?

**Comment by superarts** [comment]
Would this fix a `_catchExceptionOfKind` issue? I'm seeing this when I added Quick/Nimble to Xcode 11 via SPM:

```
Undefined symbols for architecture x86_64:
  "_catchExceptionOfKind", referenced from:
      CwlCatchException.(catchReturnTypeConverter in _841BEC3F94220F0DFD4EA4E9DDB3DC93)<A where A: __C.NSException>(_: A.Type, block: () -> ()) -> A? in CwlCatchException.o
```

**Review by mattgallagher — APPROVED** [review]

**Comment by ikesyo** [comment]
Thanks @mattgallagher

**Comment by mattgallagher** [comment]
> Would this fix a `_catchExceptionOfKind` issue? I'm seeing this when I added Quick/Nimble to Xcode 11 via SPM:
> 
> ```
> Undefined symbols for architecture x86_64:
>   "_catchExceptionOfKind", referenced from:
>       CwlCatchException.(catchReturnTypeConverter in _841BEC3F94220F0DFD4EA4E9DDB3DC93)<A where A: __C.NSException>(_: A.Type, block: () -> ()) -> A? in CwlCatchException.o
> ```

This is fixed in 2.0.0 as described here:

https://github.com/mattgallagher/CwlPreconditionTesting/issues/16#issuecomment-546559637

**Pull request merged**
