### PR TITLE
Add visionOS support

### PR DESCRIPTION
**Pull request by stonko1994**
### Description
This PR combines the following PRs:
- https://github.com/mattgallagher/CwlPreconditionTesting/pull/31
- https://github.com/skumor-foreflight/CwlPreconditionTesting/pull/1

### +1
It also updates the `podspec` files to add visionOS support through CocoaPods.

### CODE REVIEW

**Comment by stonko1994** [comment]
Before this update can be used in `Nimble` https://github.com/mattgallagher/CwlPreconditionTesting/pull/34 also needs to be merged to fix Carthage support.

**Comment by mattgallagher** [comment]
Sorry I've been a little slow to get to this. I'll try to look at these in the next day or two.

**Review by mattgallagher — APPROVED** [review]
Works for me 👍. I'll run some double checks then update the versions.

**Comment by mattgallagher** [comment]
Okay, there's a new 2.2.0 tag so it should work via Swift Package Manager. I can't push an update to Cocoapods at the moment as the latest version of `pod` refuses to lint it:

> [!] Invalid `CwlPreconditionTesting.podspec` file: undefined method `visionos' for #<Pod::Specification name="CwlPreconditionTesting">.

It looks like the "support" in 1.13 didn't really work and some additional changes will be needed to fully handle the new platform.

**Comment by stonko1994** [comment]
Can you update without linting or specify the platforms to include?

I added `--platforms="ios,tvos,watchos,macos"` in Nimble to the `pod lint` command.

**Pull request merged**
